version: "3.3"
#https://github.com/codewithrajranjan/awesome-docker-compose/blob/master/ecosystem/elasticsearch-kibana-docker-compose.yml
services:
  kibana:
    container_name: kibana
    image: public.ecr.aws/elastic/kibana:8.15.1
    environment:
      - ELASTICSEARCH_HOSTS=vm-elk.ru-central1.internal:9200
    ports:
      - 5601:5601


