version: "3.5"

services:
  filebeat:
    hostname: filebeat_nginx
    container_name: filebeat_nginx
    image: public.ecr.aws/elastic/filebeat:8.15.1
    restart: on-failure
    command: ["filebeat_start.sh"]
    user: root
    ports:
      - 9200:9200
    volumes:
      - ./filebeat/filebeat_start.sh:/usr/share/filebeat/filebeat_start.sh
      - ./filebeat/filebeat_cnf/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/filebeat_cnf/nginx.yml:/usr/share/filebeat/modules.d/nginx.yml
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/nginx:/var/log/nginx


