---
#nginxs из-за запроса fingerprint алиас на группу отрабатывает с ошибкой. отключить fibgerprint через конфиг алиаса не сработало
- name: Configure nginx
  hosts: nginx
  remote_user: gekasologub
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:    
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        
    - name: Install UFW firewall
      apt: name=ufw  

    - name: Enable UFW
      community.general.ufw:
        state: enabled
        
    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp
        
    - name: Allow all access to tcp port 22
      ufw:
        rule: allow
        port: ssh
        proto: tcp
        
    - name: copy html
      ansible.builtin.template:
        src: nginx.html.j2
        dest: /usr/share/nginx/html/index.html    

    - name: copy config
      ansible.builtin.template:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        
    - name: restart service
      ansible.builtin.service:
        name: nginx        
        state: restarted

    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
        
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /usr/local/bin/docker-compose
        owner: gekasologub
        group: gekasologub
        
    - name: copy compose
      copy:
        src: ./compose/
        dest: /home/gekasologub/
        
    - name: Change permission on myScript.sh file
      file:
        path: /home/gekasologub/filebeat/filebeat_cnf/filebeat.yml
        state: file
        owner: root
        group: root
        mode: 0755
        
    - name: Run a command docker-compose
      ansible.builtin.shell: 
        cmd: docker-compose -f filebeat_compose.yml up -d
        chdir: /home/gekasologub
        executable: /bin/bash

    - name: zabbix_agent.conf
      copy:
        src: zabbix_agent.conf
        dest: /etc/zabbix/

    - name: restart service zabbix-agent
      ansible.builtin.service:
        name: zabbix-agent        
        state: restarted
