#from public.ecr.aws/elastic/filebeat:8.15.1
#COPY ./filebeat_cnf/filebeat.yml /usr/share/filebeat/filebeat.yml
#COPY ./filebeat_cnf/nginx.yml /usr/share/filebeat/modules.d/nginx.yml
#COPY ./filebeat_start.sh filebeat_start.sh
#RUN chmod +x filebeat_start.sh