version: "3.3"

services:
  kibana:
    container_name: kibana
    hostname: kibana
    image: public.ecr.aws/elastic/kibana:8.15.1
    configs:
      - source: kibana_cnf
        target: /usr/share/kibana/config/kibana.yml
    ports:
      - 80:5601
      - 9200:9200
configs:
  kibana_cnf:
    file: ./config/kibana.yml
