---
- name: Configure nginx
  hosts: zabbix
  remote_user: gekasologub
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install UFW firewall
      apt: name=ufw  
      
    - name: Enable UFW
      community.general.ufw:
        state: enabled
        
    - name: Allow all access to port 10050 for agent
      ufw:
        rule: allow
        port: '10050'

   - name: Allow all access to port 10051 for agent
      ufw:
        rule: allow
        port: '10051'

    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp
        
    - name: Allow all access to tcp port 22
      ufw:
        rule: allow
        port: ssh
        proto: tcp
        
    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
        
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /usr/local/bin/docker-compose
        owner: gekasologub
        group: gekasologub
       
    - name: copy compose
      copy:
        src: zabbix.zip
        dest: /home/gekasologub/

    - name: Change file zabbix.zip ownership, group and permissions
      ansible.builtin.file:
        path: /home/gekasologub/zabbix.zip
        owner: gekasologub
        group: gekasologub
        mode: 0755
         
    - name: Extract zabbix.zip
      ansible.builtin.unarchive:
        src: /home/gekasologub/zabbix.zip
        dest: /home/gekasologub
        remote_src: yes
        
    - name: Run a command docker-compose
      ansible.builtin.shell: 
        cmd: docker-compose -f docker-compose.yml up -d
        chdir: /home/gekasologub/zabbix
        executable: /bin/bash
